name: linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: npm install
        run: npm install -D
      - name: run ESLint
        run: npm run lint:fix
      - name: run test cases
        run: npm run test
